xcopy /S /Y  e:\symdiff_codeplex\symdiff\Dependency\Test\siemens\print_tokens\source.bpl.2.detstubs.html htmls_8_19\siemens\print_tokens\source.bpl.2.detstubs.html
xcopy /S /Y  e:\symdiff_codeplex\symdiff\Dependency\Test\siemens\print_tokens\source.bpl.2.detstubs.nominunsat.html htmls_8_19\siemens\print_tokens\source.bpl.2.detstubs.nominunsat.html
xcopy /S /Y  e:\symdiff_codeplex\symdiff\Dependency\Test\siemens\print_tokens\source.bpl.2.html htmls_8_19\siemens\print_tokens\source.bpl.2.html
xcopy /S /Y  e:\symdiff_codeplex\symdiff\Dependency\Test\siemens\print_tokens\source.bpl.2.nominunsat.html htmls_8_19\siemens\print_tokens\source.bpl.2.nominunsat.html
xcopy /S /Y  e:\symdiff_codeplex\symdiff\Dependency\Test\siemens\print_tokens\source.bpl.3.detstubs.nominunsat.html htmls_8_19\siemens\print_tokens\source.bpl.3.detstubs.nominunsat.html
xcopy /S /Y  e:\symdiff_codeplex\symdiff\Dependency\Test\siemens\print_tokens\source.bpl.4.detstubs.nominunsat.html htmls_8_19\siemens\print_tokens\source.bpl.4.detstubs.nominunsat.html
xcopy /S /Y  e:\symdiff_codeplex\symdiff\Dependency\Test\siemens\print_tokens\source.bpl.readSet.html htmls_8_19\siemens\print_tokens\source.bpl.readSet.html
xcopy /S /Y  e:\symdiff_codeplex\symdiff\Dependency\Test\siemens\print_tokens2\source.bpl.2.detstubs.html htmls_8_19\siemens\print_tokens2\source.bpl.2.detstubs.html
xcopy /S /Y  e:\symdiff_codeplex\symdiff\Dependency\Test\siemens\print_tokens2\source.bpl.2.detstubs.nominunsat.html htmls_8_19\siemens\print_tokens2\source.bpl.2.detstubs.nominunsat.html
xcopy /S /Y  e:\symdiff_codeplex\symdiff\Dependency\Test\siemens\print_tokens2\source.bpl.2.html htmls_8_19\siemens\print_tokens2\source.bpl.2.html
xcopy /S /Y  e:\symdiff_codeplex\symdiff\Dependency\Test\siemens\print_tokens2\source.bpl.2.nominunsat.html htmls_8_19\siemens\print_tokens2\source.bpl.2.nominunsat.html
xcopy /S /Y  e:\symdiff_codeplex\symdiff\Dependency\Test\siemens\print_tokens2\source.bpl.3.detstubs.nominunsat.html htmls_8_19\siemens\print_tokens2\source.bpl.3.detstubs.nominunsat.html
xcopy /S /Y  e:\symdiff_codeplex\symdiff\Dependency\Test\siemens\print_tokens2\source.bpl.4.detstubs.nominunsat.html htmls_8_19\siemens\print_tokens2\source.bpl.4.detstubs.nominunsat.html
xcopy /S /Y  e:\symdiff_codeplex\symdiff\Dependency\Test\siemens\print_tokens2\source.bpl.readSet.html htmls_8_19\siemens\print_tokens2\source.bpl.readSet.html
xcopy /S /Y  e:\symdiff_codeplex\symdiff\Dependency\Test\siemens\replace\source.bpl.2.detstubs.html htmls_8_19\siemens\replace\source.bpl.2.detstubs.html
xcopy /S /Y  e:\symdiff_codeplex\symdiff\Dependency\Test\siemens\replace\source.bpl.2.detstubs.nominunsat.html htmls_8_19\siemens\replace\source.bpl.2.detstubs.nominunsat.html
xcopy /S /Y  e:\symdiff_codeplex\symdiff\Dependency\Test\siemens\replace\source.bpl.2.html htmls_8_19\siemens\replace\source.bpl.2.html
xcopy /S /Y  e:\symdiff_codeplex\symdiff\Dependency\Test\siemens\replace\source.bpl.2.nominunsat.html htmls_8_19\siemens\replace\source.bpl.2.nominunsat.html
xcopy /S /Y  e:\symdiff_codeplex\symdiff\Dependency\Test\siemens\replace\source.bpl.3.detstubs.nominunsat.html htmls_8_19\siemens\replace\source.bpl.3.detstubs.nominunsat.html
xcopy /S /Y  e:\symdiff_codeplex\symdiff\Dependency\Test\siemens\replace\source.bpl.4.detstubs.nominunsat.html htmls_8_19\siemens\replace\source.bpl.4.detstubs.nominunsat.html
xcopy /S /Y  e:\symdiff_codeplex\symdiff\Dependency\Test\siemens\replace\source.bpl.readSet.html htmls_8_19\siemens\replace\source.bpl.readSet.html
xcopy /S /Y  e:\symdiff_codeplex\symdiff\Dependency\Test\siemens\schedule\source.bpl.2.detstubs.html htmls_8_19\siemens\schedule\source.bpl.2.detstubs.html
xcopy /S /Y  e:\symdiff_codeplex\symdiff\Dependency\Test\siemens\schedule\source.bpl.2.detstubs.nominunsat.html htmls_8_19\siemens\schedule\source.bpl.2.detstubs.nominunsat.html
xcopy /S /Y  e:\symdiff_codeplex\symdiff\Dependency\Test\siemens\schedule\source.bpl.2.html htmls_8_19\siemens\schedule\source.bpl.2.html
xcopy /S /Y  e:\symdiff_codeplex\symdiff\Dependency\Test\siemens\schedule\source.bpl.2.nominunsat.html htmls_8_19\siemens\schedule\source.bpl.2.nominunsat.html
xcopy /S /Y  e:\symdiff_codeplex\symdiff\Dependency\Test\siemens\schedule\source.bpl.3.detstubs.nominunsat.html htmls_8_19\siemens\schedule\source.bpl.3.detstubs.nominunsat.html
xcopy /S /Y  e:\symdiff_codeplex\symdiff\Dependency\Test\siemens\schedule\source.bpl.4.detstubs.nominunsat.html htmls_8_19\siemens\schedule\source.bpl.4.detstubs.nominunsat.html
xcopy /S /Y  e:\symdiff_codeplex\symdiff\Dependency\Test\siemens\schedule\source.bpl.readSet.html htmls_8_19\siemens\schedule\source.bpl.readSet.html
xcopy /S /Y  e:\symdiff_codeplex\symdiff\Dependency\Test\siemens\tcas\source.bpl.2.detstubs.html htmls_8_19\siemens\tcas\source.bpl.2.detstubs.html
xcopy /S /Y  e:\symdiff_codeplex\symdiff\Dependency\Test\siemens\tcas\source.bpl.2.detstubs.nominunsat.html htmls_8_19\siemens\tcas\source.bpl.2.detstubs.nominunsat.html
xcopy /S /Y  e:\symdiff_codeplex\symdiff\Dependency\Test\siemens\tcas\source.bpl.2.html htmls_8_19\siemens\tcas\source.bpl.2.html
xcopy /S /Y  e:\symdiff_codeplex\symdiff\Dependency\Test\siemens\tcas\source.bpl.2.nominunsat.html htmls_8_19\siemens\tcas\source.bpl.2.nominunsat.html
xcopy /S /Y  e:\symdiff_codeplex\symdiff\Dependency\Test\siemens\tcas\source.bpl.3.detstubs.nominunsat.html htmls_8_19\siemens\tcas\source.bpl.3.detstubs.nominunsat.html
xcopy /S /Y  e:\symdiff_codeplex\symdiff\Dependency\Test\siemens\tcas\source.bpl.4.detstubs.nominunsat.html htmls_8_19\siemens\tcas\source.bpl.4.detstubs.nominunsat.html
xcopy /S /Y  e:\symdiff_codeplex\symdiff\Dependency\Test\siemens\tcas\source.bpl.readSet.html htmls_8_19\siemens\tcas\source.bpl.readSet.html
xcopy /S /Y  e:\symdiff_codeplex\symdiff\Dependency\Test\siemens\tot_info\source.bpl.2.detstubs.html htmls_8_19\siemens\tot_info\source.bpl.2.detstubs.html
xcopy /S /Y  e:\symdiff_codeplex\symdiff\Dependency\Test\siemens\tot_info\source.bpl.2.detstubs.nominunsat.html htmls_8_19\siemens\tot_info\source.bpl.2.detstubs.nominunsat.html
xcopy /S /Y  e:\symdiff_codeplex\symdiff\Dependency\Test\siemens\tot_info\source.bpl.2.html htmls_8_19\siemens\tot_info\source.bpl.2.html
xcopy /S /Y  e:\symdiff_codeplex\symdiff\Dependency\Test\siemens\tot_info\source.bpl.2.nominunsat.html htmls_8_19\siemens\tot_info\source.bpl.2.nominunsat.html
xcopy /S /Y  e:\symdiff_codeplex\symdiff\Dependency\Test\siemens\tot_info\source.bpl.3.detstubs.nominunsat.html htmls_8_19\siemens\tot_info\source.bpl.3.detstubs.nominunsat.html
xcopy /S /Y  e:\symdiff_codeplex\symdiff\Dependency\Test\siemens\tot_info\source.bpl.4.detstubs.nominunsat.html htmls_8_19\siemens\tot_info\source.bpl.4.detstubs.nominunsat.html
xcopy /S /Y  e:\symdiff_codeplex\symdiff\Dependency\Test\siemens\tot_info\source.bpl.readSet.html htmls_8_19\siemens\tot_info\source.bpl.readSet.html
xcopy /S /Y  e:\symdiff_codeplex\symdiff\Dependency\Test\space\source.bpl.2.detstubs.nominunsat.html htmls_8_19\space\source.bpl.2.detstubs.nominunsat.html
xcopy /S /Y  e:\symdiff_codeplex\symdiff\Dependency\Test\space\source.bpl.readSet.html htmls_8_19\space\source.bpl.readSet.html
